language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
  global:   #Optional
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

android:
    components:
        - platform-tools
        - tools
        - build-tools-26.0.2    #Build tool version
        - android-26            #targate api version
        - android-22
        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        #system images for emulator
        - sys-img-armeabi-v7a-android-22
        - sys-img-armeabi-v7a-android-26
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

before_script:
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target android-22 --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-window &    #Start emulator

script:
    - android-wait-for-emulator             #Run wait for the emulator script.
    - adb devices                           #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace

before_install:
    - pip install coveralls
after_success:
  ./gradlew jacocoTestReport coveralls
